;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        electric-pair-delete-pair
        end-of-buffer
        sgml-slash
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        upcase-region
        ))
